mysite/mysite/urls.py
from django.contrib import admin
from django.urls import include, path


handler404 = 'nicinterface.views.handler404'
handler500 = 'nicinterface.views.handler500'

urlpatterns = [
    path('admin', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include('nicinterface.urls')),
]

mysite/nicinterface/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.landing, name='landing'),
    path('conversion', views.conversion, name='conversion'),
    path('formconversion/', views.conversion_form_process, name="form-conversion"),
    path('conversionthanks/', views.conversion_form_redirect, name="form-conversion-thanks"),
    
    path('correlation', views.correlation, name='correlation'),
    path('correlationsession', views.correlation_inputs_session_store, name="correlation-session-store"),
    path('correlationprefilled', views.correlation_prepopulated, name="correlation-prefilled"),
    path("formcorrelation/", views.correlation_form_process, name="form-correlation"),
    path('correlationthanks/', views.correlation_form_redirect, name="form-correlation-thanks"),

    path('patientdemo/', views.patient_demo_process, name="form-patient-demo"),

    path('history/', views.past_run_provenance, name="history"),

    path('networkanalysis', views.network_analysis, name="network-analysis"),
    path('networkanalysisprocess', views.network_analysis_process, name="network-analysis-process"),
    path("downloadnetworkanalysis", views.download_network_analysis, name="download-network-analysis"),
    # path('nathanks', views.network_analysis_redirect, name="network-analysis-thanks"),
    # path('corr_history/', views.past_run_provenance, name="corr-provenance")
]

mysite/nicinterface/models.py
from django.db import models

class ConversionHistory(models.Model):
 
  your_name = models.TextField(max_length=100)
  edf_file_loc = models.TextField()
  # edf_file_loc = forms.FilePathField(path="./", allow_folders=True)
  # see diff?
  # output_csf_loc = forms.FilePathField(path="./")
  output_csf_loc = models.TextField()
  epoch_duration = models.IntegerField()
  epochs_per_segment = models.IntegerField()


class CorrelationHistory(models.Model):

  CORRELATION_METRIC_CHOICES = (
    ('pijn', 'PIJN Correlation'),
    ('pearson', 'Pearson Correlation'),
    ('phase', 'Phase Coherence Correlation'),
  )    

  csf_file_loc = models.TextField()
  
  # correlation form elements
  #pijn', 'pearson', 'phase' as a comma-delimited list
  corr_metric_list = models.CharField(max_length=25)
  # corr_output_loc = forms.FilePathField(path="./", allow_folders=True)
  corr_output_loc = models.TextField()


class CorrelationTimeHistory(models.Model):
  # Format: '16.05.14,16.10.10'  
  seizure_start_time = models.DateTimeField()
  seizure_end_time = models.DateTimeField()
  lag_window = models.DecimalField(max_digits=50, decimal_places=2)
  channel_list = models.TextField()
  correlation = models.ForeignKey(CorrelationHistory, on_delete=models.CASCADE)

mysite/nicinterface/forms.py
from django import forms
from django.forms import BaseFormSet
from django.forms import formset_factory
from django.core.validators import RegexValidator

class ConversionForm(forms.Form):
 
  conv_patient_mrn = forms.IntegerField(label="Patient ID (Medical Record Number)", widget=forms.TextInput(attrs={'placeholder': '12345'}))
  edf_file_loc = forms.CharField(label='Path to EDF Files', strip=True, widget=forms.TextInput(attrs={'placeholder': '/path/to/edf/directory'}))
  # edf_file_loc = forms.FilePathField(path="./", allow_folders=True)
  # see diff?
  # output_csf_loc = forms.FilePathField(path="./")
  output_csf_loc = forms.CharField(label='Desired Full Output Path of CSF Files', strip=True, widget=forms.TextInput(attrs={'placeholder': '/path/to/csf/output/directory'}))
  epoch_duration = forms.IntegerField()
  epochs_per_segment = forms.IntegerField()


class CorrelationInputForm(forms.Form):
    # create an extra set of fields
    
    # Format: '16.05.14,16.10.10'  
    # Should ALWAYS be day, month, year for CSFwebservices to work
    seizure_start_time = forms.DateTimeField(input_formats=['%d.%m.%y,%H.%M.%S',], 
      label="Event Start Time", widget=forms.TextInput(attrs={'placeholder': 'e.g. 16.03.20,10.15.05'}))

    seizure_end_time = forms.DateTimeField(input_formats=['%d.%m.%y,%H.%M.%S',], 
      label="Event End Time", widget=forms.TextInput(attrs={'placeholder': 'e.g. 16.03.20,10.15.45'}))
    
    lag_window = forms.DecimalField(decimal_places=2, label="Lag Window (in seconds)", 
      widget=forms.TextInput(attrs={'placeholder': 'e.g. 0.10'}))
    
    channel_list = forms.CharField(label="List of Channels (comma-separated)", strip=True, 
      widget=forms.TextInput(attrs={'placeholder': 'e.g. lk1,lk3,lj1'}))
    
    corr_output_loc = forms.CharField(label='Path to Correlation Metrics Output File', strip=True, 
      widget=forms.TextInput(attrs={'placeholder': '/output/path/of/measures.txt'}), validators=[RegexValidator(regex=r"\.txt$", message="Must be a .txt file")])


class BaseCorrelationInputFormSet(BaseFormSet):
  def clean(self):
      """Checks that no two correlation inputs have the same output file loc."""
      if any(self.errors):
          # Don't bother validating the formset unless each form is valid on its own
          return
      corr_output_locs = []
      for form in self.forms:
          corr_output_loc = form.cleaned_data['corr_output_loc']
          if corr_output_loc in corr_output_locs:
              raise forms.ValidationError("Each seizure window must have its own output file.")
          corr_output_locs.append(corr_output_loc)  


CorrelationInputFormSet = formset_factory(CorrelationInputForm, formset=BaseCorrelationInputFormSet, extra=1)


class CorrelationForm(forms.Form):
  CORRELATION_METRIC_CHOICES = (
    ('pijn', 'PIJN Correlation'),
    ('pearson', 'Pearson Correlation'),
    ('phase', 'Phase Coherence Correlation'),
  )    

  corr_patient_mrn = forms.IntegerField(label="Patient ID (Medical Record Number)", widget=forms.TextInput(attrs={'placeholder': '12345'}))
  csf_file_loc = forms.CharField(label='Full Path of CSF Files', strip=True,  widget=forms.TextInput(attrs={'placeholder': '/path/to/csf/directory'}))
  # correlation form elements
  corr_metric_list = forms.MultipleChoiceField(choices=CORRELATION_METRIC_CHOICES, widget=forms.CheckboxSelectMultiple)
  # corr_output_loc = forms.FilePathField(path="./", allow_folders=True)


class PatientDemoForm(forms.Form):
  patient_mrn = forms.IntegerField(label="Patient ID (Medical Record Number)")
  epi_zone_locale = forms.CharField(widget=forms.Textarea, label="Localization of Epileptic Zone")
  seiz_semiology = forms.CharField(widget=forms.Textarea, label="Seizure Semiology")
  seiz_etiology = forms.CharField(widget=forms.Textarea, label="Etiology")
  seiz_freq = forms.CharField(label="Seizure Frequency")
  med_conds = forms.CharField(widget=forms.Textarea, label="Related Medical Conditions")
  pt_age = forms.IntegerField(label="Patient Age")
  pt_gender = forms.CharField(label="Patient Gender")
  discharge_sum = forms.FileField(label="Upload Patient Discharge Summary")

class NetworkAnalysisForm(forms.Form):

  NETWORK_ANALYSIS_MEASURES = (
    ('degreedist', 'Degree Distribution'),
    ('charpathlength', 'Characteristic Path Length'),
    ('globaleff', 'Global Efficiency'),
    ('numcliques', 'Number of Cliques'),    
  )

  CORRELATION_MEASURES = (
    ('PHASE', 'Phase Coherence Correlation'),
    ('PIJN', 'Nonlinear Correlation Coefficient'),
    ('PEARSON', "Pearson's Coefficient"),
  )


  network_analysis_list = forms.MultipleChoiceField(choices=NETWORK_ANALYSIS_MEASURES, widget=forms.SelectMultiple)
  correlation_measure_list = forms.MultipleChoiceField(choices=CORRELATION_MEASURES, widget=forms.SelectMultiple)
  network_analysis_output_file = forms.CharField(label='Network Analysis Output File Name (.txt)', strip=True,  
    widget=forms.TextInput(attrs={'placeholder': 'e.g. na_file.txt'}), validators=[RegexValidator(regex=r"\.txt$", message="Must be a .txt file")])

class AdjacencyMatrixForm(forms.Form):

  seizure_event_name = forms.CharField(label='Name of Seizure Event', strip=True,  widget=forms.TextInput(attrs={'placeholder': 'e.g. ictal event 1'}))
  corr_output_loc = forms.CharField(label='Full Path of Correlation Measure File (.txt)', strip=True,  
    widget=forms.TextInput(attrs={'placeholder': '/path/to/correlation/file.txt'}), validators=[RegexValidator(regex=r"\.txt$", message="Must be a .txt file")])


AdjacencyMatrixFormset = formset_factory(AdjacencyMatrixForm, formset=BaseCorrelationInputFormSet, extra=1)

mysite/nicinterface/templates/nicinterface/conversionformthanks.html
{% extends "nicinterface/base.html" %}

{% block title %}Thanks for submitting!{% endblock %}

{% block content %}
<link rel="stylesheet" href="{% static 'nicinterface/css/conversionformthanks.css' %}">

{% if status_server_error %}
	<div class="container">
	  <div class="row justify-content-md-center">
	    <div class="col-lg-9">
	      <div class="alert alert-danger alert-dismissible fade show" role="alert">
	         A server error occurred and the status file either does not exist or could not be read. Please submit the form again. 
	        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
	          <span aria-hidden="true">&times;</span>
	        </button>
	      </div>
	    </div>
	  </div>
	</div>
{% endif %}

<div class="thanks-title">
	<h3>Thanks for submitting! Your files are being converted!</h3>
	<h5>(The page will automatically refresh every few minutes)</h5>
</div>

<div class="container">    
    <div class="row">
		<div class="col-6">
	    </div>
		<div class="col-6">

	    </div>
	</div>
	<div class="row">
    	<div class="col status-container-left">
	    	<h4 class="status-title">Current Status</h4>
			<div class="row status-group first-status-group">
				<p class="status-label">Current File: </p>
			</div>
			<div class="row justify-content-center status-group">
				<p class="status">{{ curr_file }}</p>
			</div>
			<div class="row status-group">			
				<p class="status-label">Current Step: </p>
			</div>
			<div class="row justify-content-center status-group">
				<p class="status" id="curr-step-id">{{ curr_step }}</p>
			</div>
			<div class="row status-group">
				<p class="status-label">Last Updated: </p>				
			</div>
			<div class="row justify-content-center status-group">
				<p class="status">{{ curr_time }}</p>
			</div>
		</div>
		<div class="col status-container-right">
	    	<h4 class="status-title">Status of Workflow Execution</h4>			
			<img class="status-image rounded mx-auto d-block" src="{{ status_workflow_img }}" alt="Conversion Workflow SVG">	
		</div>
    </div>	
</div>

<!-- Not working right now, random numbers instead of in order. TODO: Fix from Taverna Workflow side probably
	<div class="progress status-bar">
		<div class="progress-bar" role="progressbar" style="width: {{ fraction_complete }}%" aria-valuenow="{{ fraction_complete }}" aria-valuemin="0" aria-valuemax="100">{{ fraction_complete }}%</div>
	</div>    	
-->
<!-- Modal -->
<div class="modal fade" id="conversion-modal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Conversion Done!</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
      	<i>(Double check that the status underneath matches the input values you entered to ensure conversion run completion. This popup may refer to the previous run.)</i>
      	</br>
      	</br>      	
      	Now that your files are in CSF format, we can begin the network analysis. We start with calculating coupling measures between electrodes in the next form. We support a number of coupling measures. Please click the button below to move to the next step!
		<div class="row justify-content-center" id="modal-na-button">
	    	  <a href="{% url 'correlation' %}" class="btn btn-primary" role="button">To Correlation</a>
	    </div>	      	
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>    


<script type="text/javascript">


	window.setTimeout(function () {
		document.location.reload(true);
	    // location.href = "{% url 'form-correlation-thanks' %}";
	}, 30000); // refresh/redirect after 30 seconds.
	// 300000 == 5 minutes

	$( document ).ready(function() {
		if ($("#curr-step-id").text() === "END-CONVERSION" && "{{status_server_error}}" !== "True") {
			$("#conversion-modal").modal();
		}
	    
	});		

</script>

{% endblock %}

mysite/nicinterface/templates/nicinterface/main-conversion.html
{% extends "nicinterface/base.html" %}

{% load widget_tweaks %}

{% block title %}NIC Conversion{% endblock %}

{% block content %}

    <h1>Conversion Workflow</h1>

    <h3>Use the form below to convert your EDF files into CSF Files!</h3>
    </br>
    {% if conversion_server_error %}
		<div class="container">
		  <div class="row justify-content-md-center">
		    <div class="col-lg-9">
		      <div class="alert alert-danger alert-dismissible fade show" role="alert">
		         There was a server error that occurred. Please try resubmitting the conversion form or contacting us and we'll get back to you!
		        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
		          <span aria-hidden="true">&times;</span>
		        </button>
		      </div>
		    </div>
		  </div>
		</div>
    {% endif %}

	{% if form.errors %}
	    {% for field in form %}
	        {% for error in field.errors %}
	            <div class="alert alert-danger">
	                <strong>{{ field.label }}: {{ error|escape }}</strong>
	            </div>
	        {% endfor %}
	    {% endfor %}
	    {% for error in form.non_field_errors %}
	        <div class="alert alert-danger">
	            <strong>{{ error|escape }}</strong>
	        </div>
	    {% endfor %}
	{% endif %}    

    <div class="row justify-content-center">
    	<div class="col-6">
		<form action="{% url 'form-conversion' %}" method="post">
		    {% csrf_token %}
		    {% if patient_id %}
			    <div class="form-group">
				    <label for="{{ form.conv_patient_mrn.id_for_label }}">{{form.conv_patient_mrn.label}}</label>
						<input type="text" name="conv_patient_mrn" placeholder="12345" class="form-control" required="" id="id_conv_patient_mrn" value="{{ patient_id }}">        
				</div>
			{% else %}
			    <div class="form-group">
				    <label for="{{ form.conv_patient_mrn.id_for_label }}">{{form.conv_patient_mrn.label}}</label>
				        {% render_field form.conv_patient_mrn class+="form-control" %}
				</div>
			{% endif %}			

		    <div class="form-group">
			    <label for="{{ form.edf_file_loc.id_for_label }}">{{form.edf_file_loc.label}}</label>
		        {% render_field form.edf_file_loc class+="form-control" %}
			</div>

		    <div class="form-group">
			    <label for="{{ form.output_csf_loc.id_for_label }}">{{form.output_csf_loc.label}}</label>
		        {% render_field form.output_csf_loc class+="form-control" %}
			</div>

		    <div class="form-group">
			    <label for="{{ form.epoch_duration.id_for_label }}">{{form.epoch_duration.label}}</label>
		        {% render_field form.epoch_duration class+="form-control" %}
			</div>

		    <div class="form-group">
			    <label for="{{ form.epochs_per_segment.id_for_label }}">{{form.epochs_per_segment.label}}</label>
		        {% render_field form.epochs_per_segment class+="form-control" %}
			</div>

	    <div class="row justify-content-center">
	        <div class="col-5">
	        	<button type="submit" class="btn btn-block btn-primary">Run Conversion</button>
	    	</div>
	    </div>
		</form>
		</div>
	</div>

    <script>
		$( document ).ready(function() {

			if (sessionStorage.getItem("conv_patient_id") !== null){
				$("#id_conv_patient_mrn").val(sessionStorage.getItem("conv_patient_id"))
		        sessionStorage.removeItem("conv_patient_id");
			}
			if(sessionStorage.getItem("edf_file_loc") !== null){
				$("#id_edf_file_loc").val(sessionStorage.getItem("edf_file_loc"))	
				sessionStorage.removeItem("edf_file_loc");
			}    
		    if(sessionStorage.getItem("output_file_loc") !== null){
		    	$("#id_output_csf_loc").val(sessionStorage.getItem("output_file_loc"))
		    	sessionStorage.removeItem("output_file_loc");
		    }
		    if(sessionStorage.getItem("epoch_duration") !== null){
			    $("#id_epoch_duration").val(sessionStorage.getItem("epoch_duration"))  
		        sessionStorage.removeItem("epoch_duration");

		    }
		    if(sessionStorage.getItem("epoch_per_segment") !== null){
		    	$("#id_epochs_per_segment").val(sessionStorage.getItem("epoch_per_segment"))    	
			    sessionStorage.removeItem("epoch_per_segment");
		    }        
		    if (localStorage.getItem("currPatientID") !== null && 
		    		$("#id_conv_patient_mrn").val() === "") {
		      $("#id_conv_patient_mrn").val(localStorage.getItem("currPatientID"));
		    }    


		});
    </script>

{% endblock %}

mysite/nicinterface/templates/nicinterface/main-correlation.html
{% extends "nicinterface/base.html" %}

{% load widget_tweaks %}

{% block title %}NIC Correlation{% endblock %}

{% block content %}

    <link rel="stylesheet" href="{% static 'nicinterface/css/main-correlation.css' %}">


    <h1 class="corr-workflow-page-title">Correlation Workflow</h1>


	<form class="form-horizontal" method="POST" action="{% url 'form-correlation' %}">
    <h3>Use the form below to calculate coupling measures on your CSF Files!</h3>
    <hr/>

    {% if correlation_server_error %}
    <div class="container">
      <div class="row justify-content-md-center">
        <div class="col-lg-9">
          <div class="alert alert-danger alert-dismissible fade show" role="alert">
             There was a server error that occurred. Please try resubmitting the correlation form or contacting us and we'll get back to you!
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
        </div>
      </div>
    </div>
    {% endif %}

  {% if correlation_form.errors %}
      {% for field in correlation_form %}
          {% for error in field.errors %}
              <div class="alert alert-danger">
                  <strong>{{ field.label }}: {{ error|escape }}</strong>
              </div>
          {% endfor %}
      {% endfor %}
      {% for error in correlation_form.non_field_errors %}
          <div class="alert alert-danger">
              <strong>{{ error|escape }}</strong>
          </div>
      {% endfor %}
  {% endif %}    


    <h5 class="correlation-step-heading">Step 1: Select the location of your CSF Files for the selected patient.</h5>
    {% csrf_token %}
    <div class="row justify-content-md-center">
      <div class="col-6">
          {% if patient_id %}
              <label for="{{ correlation_form.corr_patient_mrn.id_for_label }}">{{correlation_form.corr_patient_mrn.label}}</label>
              <input type="text" name="corr_patient_mrn" placeholder="12345" class="form-control" required="" id="id_corr_patient_mrn" value="{{ patient_id }}"> 
          {% else %}
            <label>{{correlation_form.corr_patient_mrn.label}}</label>
            {% render_field correlation_form.corr_patient_mrn class+="form-control" %}
          {% endif %}     
          <label>{{correlation_form.csf_file_loc.label}}</label>
          <div class="input-group">
              {% render_field correlation_form.csf_file_loc class+="form-control" %}
          </div>
          <label>{{correlation_form.corr_output_loc.label}}</label>
          <div class="input-group">
              {% render_field correlation_form.corr_output_loc class+="form-control" %}
          </div>
      </div>      
    </div>
    <h5 class="correlation-step-heading">Step 2: Select the coupling measures you would like to calculate.</h5>
  	<div class="row justify-content-md-center">
  		<div class="col-6">
  <!--		    <label style="padding-left: 35px;">{{correlation_form.corr_metric_list.label}}</label>
   			{% for checkbox in correlation_form.corr_metric_list %}
  			    <label class="btn btn-primary">
  			    {{ checkbox.tag }} {{ checkbox.choice_label }}
  			    </label>
  			{% endfor %}	 -->    
  		    {% render_field correlation_form.corr_metric_list class+="" %}
  		</div>
  	</div>

    <h5 class="correlation-step-heading">Step 3: Enter the event windows for the given patient.</h5>
    {% if not corr_seiz_prefill_inputs %}
      {% if formset.errors %}
        {% for dict in formset.errors %}
            {% for field, error_list in dict.items %}
              {% for error in error_list %}
                  <div class="alert alert-danger">
                      <strong>Error in entry {{ forloop.parentloop.parentloop.counter }} - Field {{ field }}: {{ error|escape }}</strong>
                  </div>
              {% endfor %}    
            {% endfor %}
        {% endfor %}
        {% for error in formset.non_field_errors %}
            <div class="alert alert-danger">
                <strong>{{ error|escape }}</strong>
            </div>
        {% endfor %}
      {% endif %}    

      <table class="table">
          {{ formset.management_form }}
          {% for form in formset.forms %}
              {% if forloop.first %}
                  <thead>
                  <tr>
                      {% for field in form.visible_fields %}
                          <th>{{ field.label|capfirst }}</th>
                      {% endfor %}
                  </tr>
                  </thead>
              {% endif %}
              <tr class="formset_row">
                  {% for field in form.visible_fields %}
                      <td>
                          {# Include the hidden fields in the form #}
                          {% if forloop.first %}
                              {% for hidden in form.hidden_fields %}
                                  {{ hidden }}
                              {% endfor %}
                          {% endif %}
                          {{ field }}
                      </td>
                  {% endfor %}
              </tr>
          {% endfor %}
      </table>
    {% else %}

      {% if formset.errors %}
        {% for dict in formset.errors %}
            {% for field, error_list in dict.items %}
              {% for error in error_list %}
                  <div class="alert alert-danger">
                      <strong>Error in entry {{ forloop.parentloop.parentloop.counter }} - Field {{ field }}: {{ error|escape }}</strong>
                  </div>
              {% endfor %}    
            {% endfor %}
        {% endfor %}
        {% for error in formset.non_field_errors %}
            <div class="alert alert-danger">
                <strong>{{ error|escape }}</strong>
            </div>
        {% endfor %}
      {% endif %}    


      <table class="table">
          {{ formset.management_form }}

          {% for form in formset.forms %}
              {% if forloop.first %}
                  <thead>
                  <tr>
                      {% for field in form.visible_fields %}
                          <th>{{ field.label|capfirst }}</th>
                      {% endfor %}
                  </tr>
                  </thead>
              {% endif %}
              {% for seiz_input_prefill in corr_seiz_prefill_inputs  %}
                <tr class="formset_row">
                        {# Include the hidden fields in the form #}
                        {% for hidden in form.hidden_fields %}
                            {{ hidden }}
                        {% endfor %}
                        <td>
                          <input type="text" name="form-{{ forloop.counter0 }}-seizure_start_time" placeholder="e.g. 16.03.20,10.15.05" id="id_form-{{ forloop.counter0 }}-seizure_start_time" value="{{ seiz_input_prefill.seizure_start }}">
                        </td>
                        <td>
                          <input type="text" name="form-{{ forloop.counter0 }}-seizure_end_time" placeholder="e.g. 16.03.20,10.15.45" id="id_form-{{ forloop.counter0 }}-seizure_end_time" value="{{ seiz_input_prefill.seizure_end }}">
                        </td>
                        <td>
                          <input type="text" name="form-{{ forloop.counter0 }}-lag_window" placeholder="e.g. 0.10" id="id_form-{{ forloop.counter0 }}-lag_window" value="{{ seiz_input_prefill.lag_window }}">
                        </td>
                        <td>
                          <input type="text" name="form-{{ forloop.counter0 }}-channel_list" placeholder="e.g. lk1,lk3,lj1" id="id_form-{{ forloop.counter0 }}-channel_list" value="{{ seiz_input_prefill.channel_list }}">
                        </td>
                        <td>
                          <input type="text" name="form-{{ forloop.counter0 }}-corr_output_loc" placeholder="e.g. /output/path/of/measures" id="id_form-{{ forloop.counter0 }}-corr_output_loc" value="{{ seiz_input_prefill.corr_output_loc }}">
                        </td>                            
                </tr>
              {% endfor %}
          {% endfor %}
      </table>
    {% endif %}

  	<div class="row justify-content-center">
  	    <div class="col-3">
  	        <button type="submit" class="btn btn-block btn-primary">Run Correlations</button>
  	    </div>
  	</div>
	</form>

<script src="{% static 'nicinterface/js/jquery.formset.js' %}"></script>
<!-- <script src="{% static 'nicinterface/js/main-correlation.js' %}"></script> -->
<script>

  $( document ).ready(function() {

    if (sessionStorage.getItem("corr_metrics") !== null){
      var metrics = sessionStorage.getItem("corr_metrics");
          var metrics_list = metrics.split(",");
          for (var i = 0; i < metrics_list.length; i++){
              if(metrics_list[i] == "pijn"){
                  $("#id_corr_metric_list_0").attr("checked", true);
              } else if (metrics_list[i] == "pearson") {
                  $("#id_corr_metric_list_1").attr("checked", true);
              } else if (metrics_list[i] == "phase") {
                  $("#id_corr_metric_list_2").attr("checked", true);
              }
          }
          sessionStorage.removeItem("corr_metrics");
    }
    if(sessionStorage.getItem("csf_file_loc") !== null){
      $("#id_csf_file_loc").val(sessionStorage.getItem("csf_file_loc")) 
      sessionStorage.removeItem("csf_file_loc");

      // we also want to increase the hidden input field to the right number of forms in formset
      var numItems = $('.formset_row.dynamic-form').length;
      $("#id_form-TOTAL_FORMS").val(numItems);

    }    
      // if(sessionStorage.getItem("corr_output_loc") !== null){
      //   $("#id_corr_output_loc").val(sessionStorage.getItem("corr_output_loc"))
      //   sessionStorage.removeItem("corr_output_loc");
      // }
      if(sessionStorage.getItem("corr_patient_id") !== null){
        $("#id_corr_patient_mrn").val(sessionStorage.getItem("corr_patient_id"))  
          sessionStorage.removeItem("corr_patient_id");
      }

      // this one is for the link from the main page
      if (localStorage.getItem("currPatientID") !== null) {
        $("#id_corr_patient_mrn").val(localStorage.getItem("currPatientID"));
      }    

    });

    $('.formset_row').formset({
        addText: 'Add Seizure Event',
        deleteText: 'Remove Seizure Event'
    });

</script>

{% endblock %}